#if !canImport(ObjectiveC)
import XCTest

extension RampartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RampartTests = [
        ("testCompareEndpoint", testCompareEndpoint),
        ("testDetermineRelation", testDetermineRelation),
        ("testInvertedRelation", testInvertedRelation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RampartTests.__allTests__RampartTests),
    ]
}
#endif
